CREATE TABLE `ACESSO` (
 `ID_ROTINA` int DEFAULT NULL,
 `ID_ACESSO` int DEFAULT NULL,
 KEY `ID_ROTINA_FK` (`ID_ROTINA`),
 KEY `ID_ACESSOFKY` (`ID_ACESSO`),
 CONSTRAINT `ID_ACESSOFKY` FOREIGN KEY (`ID_ACESSO`) REFERENCES `CONTROLE_ACESSO` (`ID_ACESSO`),
 CONSTRAINT `ID_ROTINA_FK` FOREIGN KEY (`ID_ROTINA`) REFERENCES `ROTINA` (`ID_ROTINA`)
);

CREATE TABLE `ARMAZENAMENTOS` (
 `armcodigo` int NOT NULL AUTO_INCREMENT,
 `localizacao` int DEFAULT NULL,
 `prdcodigo` int DEFAULT NULL,
 `nome` varchar(100) DEFAULT NULL,
 `endereco` varchar(8) DEFAULT NULL,
 `capacidade` varchar(100) DEFAULT NULL,
 `dtinstalacao` date DEFAULT NULL,
 `dtmodificacao` date DEFAULT NULL,
 PRIMARY KEY (`armcodigo`),
 KEY `prdcodigo` (`prdcodigo`),
 CONSTRAINT `ARMAZENAMENTOS_ibfk_1` FOREIGN KEY (`prdcodigo`) REFERENCES `PRODUTOS` (`PRDCODIGO`)
);

CREATE TABLE `CARTOES` (
 `CRTCODIGO` int NOT NULL AUTO_INCREMENT,
 `CRTCLIENTE` int DEFAULT NULL,
 `CRTNUMERO` int NOT NULL,
 `CRTTIPO` varchar(50) NOT NULL,
 `CRTEMISSAO` date DEFAULT NULL,
 `CRTVALID` date DEFAULT NULL,
 `CRTSTATUS` varchar(20) DEFAULT NULL,
 `CRTLIMIT` decimal(10,2) DEFAULT NULL,
 `CRTPONT` int DEFAULT '0',
 PRIMARY KEY (`CRTCODIGO`),
 KEY `FK_CRTCLIENTE` (`CRTCLIENTE`),
 CONSTRAINT `FK_CRTCLIENTE` FOREIGN KEY (`CRTCLIENTE`) REFERENCES `CLIENTES` (`CLICODIGO`)
);

CREATE TABLE `CATEGORIAS` (
 `catcodigo` int NOT NULL AUTO_INCREMENT,
 `nome` varchar(100) NOT NULL,
 `descricao` text,
 `tipo` varchar(100) DEFAULT NULL,
 PRIMARY KEY (`catcodigo`)
);

CREATE TABLE `CLIENTES` (
 `CLICODIGO` int NOT NULL AUTO_INCREMENT,
 `CLICPF` varchar(15) NOT NULL,
 `CLINOME` varchar(150) NOT NULL,
 `CLIDTNASC` date DEFAULT NULL,
 `CLIEMAIL` varchar(150) DEFAULT NULL,
 `CLITEL1` varchar(20) DEFAULT NULL,
 `CLITEL2` varchar(20) DEFAULT NULL,
 `CLISENHA` varchar(500) DEFAULT NULL,
 PRIMARY KEY (`CLICODIGO`)
);

CREATE TABLE `CONTROLE_ACESSO` (
 `ID_ACESSO` int NOT NULL AUTO_INCREMENT,
 `USUARIO` varchar(100) NOT NULL,
 `SENHA` varchar(10) NOT NULL,
 `TIPO_USUARIO` varchar(2) NOT NULL,
 `STATUS` varchar(20) DEFAULT NULL,
 `DATA_CRIACAO` datetime DEFAULT NULL,
 `DATA_ACESSO` datetime DEFAULT NULL,
 PRIMARY KEY (`ID_ACESSO`)
);

CREATE TABLE `CUPOM` (
 `cpmId` int NOT NULL AUTO_INCREMENT,
 `cpmCodigo` varchar(20) NOT NULL,
 `cpmDesc` varchar(100) NOT NULL,
 `cpmTipo` int DEFAULT NULL,
 `cpmValor` decimal(10,0) NOT NULL,
 `cpmVldInic` date NOT NULL,
 `cpmVldFin` date NOT NULL,
 `cpmAtivo` tinyint(1) NOT NULL,
 PRIMARY KEY (`cpmId`),
 KEY `cpmTipo` (`cpmTipo`),
 CONSTRAINT `CUPOM_ibfk_1` FOREIGN KEY (`cpmTipo`) REFERENCES `TIPO_CUPOM` (`tipoCpm`)
);

CREATE TABLE `ENTREGA` (
 `ID` int NOT NULL,
 `ID_TRANSPORTADORA` int NOT NULL,
 `ID_PEDIDO` int NOT NULL,
 `DATA_ENTREGA` date DEFAULT NULL,
 `FRETE` decimal(10,0) DEFAULT NULL,
 `MOTORISTA` varchar(150) DEFAULT NULL,
 PRIMARY KEY (`ID`),
 KEY `FK_ENTREGATRANSP` (`ID_TRANSPORTADORA`),
 KEY `FK_ENTREGAPEDIDO` (`ID_PEDIDO`),
 CONSTRAINT `FK_ENTREGAPEDIDO` FOREIGN KEY (`ID_PEDIDO`) REFERENCES `PEDIDO` (`pddCod`),
 CONSTRAINT `FK_ENTREGATRANSP` FOREIGN KEY (`ID_TRANSPORTADORA`) REFERENCES `TRANSPORTADORA` (`ID`)
);

CREATE TABLE `ESTOQUE` (
 `STQREFEENCIA` int NOT NULL,
 `STQPRODUTO` int NOT NULL,
 `STQLOTE` int NOT NULL,
 `STQUANTIDADE` int DEFAULT NULL,
 PRIMARY KEY (`STQREFEENCIA`,`STQPRODUTO`,`STQLOTE`),
 KEY `FK_ESTOQ` (`STQPRODUTO`),
 CONSTRAINT `FK_ESTOQ` FOREIGN KEY (`STQPRODUTO`) REFERENCES `PRODUTOS` (`PRDCODIGO`)
);

CREATE TABLE `FN_CARGO` (
 `ID_CARGO` int NOT NULL AUTO_INCREMENT,
 `CARGONOME` varchar(255) NOT NULL,
 `CARGOSALARIO` decimal(10,5) DEFAULT NULL,
 `CARGONIVEL` int NOT NULL,
 PRIMARY KEY (`ID_CARGO`)
);

CREATE TABLE `FN_FERIAS` (
 `ID_FERIAS` int NOT NULL AUTO_INCREMENT,
 `FERIASDATAINICIO` date NOT NULL,
 `FERIASDATAFIM` date NOT NULL,
 `FERIASDIASTOT` int NOT NULL,
 `FERIASSTATUS` enum('S','N') DEFAULT NULL,
 `ID_FUNCIONARIOS` int NOT NULL,
 PRIMARY KEY (`ID_FERIAS`),
 KEY `funcio_ferias` (`ID_FUNCIONARIOS`),
 CONSTRAINT `funcio_ferias` FOREIGN KEY (`ID_FUNCIONARIOS`) REFERENCES `FUNCIONARIOS` (`ID_FUNCIONARIOS`) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE `FN_TURNO` (
 `ID_TURNO` int NOT NULL AUTO_INCREMENT,
 `TRNPERIODO` varchar(255) NOT NULL,
 `TRNHORAINICIO` datetime NOT NULL,
 `TRNHORAFIM` datetime NOT NULL,
 `TRNCARGAHORARIA` int NOT NULL,
 PRIMARY KEY (`ID_TURNO`)
);

CREATE TABLE `FORMAPAGAMENTO` (
 `id` int NOT NULL AUTO_INCREMENT,
 `descricao` varchar(255) DEFAULT NULL,
 `ativo` bit(1) DEFAULT NULL,
 PRIMARY KEY (`id`)
);

CREATE TABLE `FORNECEDORES` (
 `FRNCODIGO` int NOT NULL,
 `FRNCNPJ` char(15) DEFAULT NULL,
 `FRNRAZAOSOCIAL` varchar(250) DEFAULT NULL,
 `FRNFANTASIA` varchar(250) DEFAULT NULL,
 `FRNENDERECO` char(8) DEFAULT NULL,
 `FRNENDCOMPL` varchar(50) DEFAULT NULL,
 `FRNCONTATO` varchar(50) DEFAULT NULL,
 PRIMARY KEY (`FRNCODIGO`)
);

CREATE TABLE `FUNCIONARIOS` (
 `ID_FUNCIONARIOS` int NOT NULL AUTO_INCREMENT,
 `FNNOME` varchar(255) NOT NULL,
 `FNIDADE` int NOT NULL,
 `ID_CARGO` int NOT NULL,
 `ID_TURNO` int NOT NULL,
 `FNSTATUS` enum('S','N') DEFAULT NULL,
 PRIMARY KEY (`ID_FUNCIONARIOS`),
 KEY `cargo_funci` (`ID_TURNO`),
 CONSTRAINT `cargo_funci` FOREIGN KEY (`ID_TURNO`) REFERENCES `FN_CARGO` (`ID_CARGO`) ON DELETE RESTRICT ON UPDATE RESTRICT,
 CONSTRAINT `turno_funci` FOREIGN KEY (`ID_TURNO`) REFERENCES `FN_TURNO` (`ID_TURNO`) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE `INTERACOES` (
 `id_interacao` int NOT NULL,
 `id_suporte` int NOT NULL,
 `data_interacao` date NOT NULL,
 `tipo_interacao` varchar(50) NOT NULL,
 `descricao` text,
 PRIMARY KEY (`id_interacao`),
 KEY `id_suporte` (`id_suporte`),
 CONSTRAINT `INTERACOES_ibfk_1` FOREIGN KEY (`id_suporte`) REFERENCES `SUPORTE` (`id_suporte`)
);

CREATE TABLE `INVENTARIO` (
 `INVTCODIGO` int NOT NULL AUTO_INCREMENT,
 `IVNTSALDO` int DEFAULT NULL,
 `IVNTSALDOATUAL` int NOT NULL,
 `IVNTCONTAGEM` int DEFAULT NULL,
 `IVNTRECONTAGEM` int DEFAULT NULL,
 PRIMARY KEY (`INVTCODIGO`)
);

CREATE TABLE `ITEM_PEDIDO` (
 `itnCod` int NOT NULL,
 `itnPdd` int NOT NULL,
 `itnPrd` int NOT NULL,
 `itnVlr` decimal(10,0) DEFAULT NULL,
 `itnQntd` int DEFAULT NULL,
 PRIMARY KEY (`itnCod`,`itnPdd`),
 KEY `itnPdd` (`itnPdd`),
 CONSTRAINT `ITEM_PEDIDO_ibfk_1` FOREIGN KEY (`itnPdd`) REFERENCES `PEDIDO` (`pddCod`)
);

CREATE TABLE `ITENS` (
 `id` int NOT NULL AUTO_INCREMENT,
 `FK_docto` int DEFAULT NULL,
 `FK_prod` int DEFAULT NULL,
 `quantidade` int DEFAULT NULL,
 `valor_unit` decimal(10,2) DEFAULT NULL,
 `valor_total` decimal(10,2) DEFAULT NULL,
 PRIMARY KEY (`id`)
);

CREATE TABLE `LOTES` (
 `lotcodigo` int NOT NULL AUTO_INCREMENT,
 `armcodigo` int DEFAULT NULL,
 `catcodigo` int DEFAULT NULL,
 `prdcodigo` int DEFAULT NULL,
 `numlote` int DEFAULT NULL,
 `dataproducao` date DEFAULT NULL,
 `validade` varchar(50) DEFAULT NULL,
 `dtexpiracao` date DEFAULT NULL,
 `dtentrada` date DEFAULT NULL,
 PRIMARY KEY (`lotcodigo`),
 KEY `armcodigo` (`armcodigo`),
 KEY `catcodigo` (`catcodigo`),
 KEY `prdcodigo` (`prdcodigo`),
 CONSTRAINT `LOTES_ibfk_1` FOREIGN KEY (`armcodigo`) REFERENCES `ARMAZENAMENTOS` (`armcodigo`),
 CONSTRAINT `LOTES_ibfk_2` FOREIGN KEY (`catcodigo`) REFERENCES `CATEGORIAS` (`catcodigo`),
 CONSTRAINT `LOTES_ibfk_3` FOREIGN KEY (`prdcodigo`) REFERENCES `PRODUTOS` (`PRDCODIGO`)
);

CREATE TABLE `MOVIMENTACAO` (
 `MVTCODIGO` int NOT NULL AUTO_INCREMENT,
 `MVTIPOMOV` int DEFAULT NULL,
 `MVTQTDE` int NOT NULL,
 `MVTLOTE` varchar(30) NOT NULL,
 PRIMARY KEY (`MVTCODIGO`),
 KEY `tpm_mvt` (`MVTIPOMOV`),
 CONSTRAINT `tpm_mvt` FOREIGN KEY (`MVTIPOMOV`) REFERENCES `TIPO_MOVIMENTO` (`tpmCodigo`) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE `PEDIDO` (
 `pddCod` int NOT NULL AUTO_INCREMENT,
 `pddCli` int DEFAULT NULL,
 `pddData` datetime NOT NULL,
 `pddTipo` int NOT NULL,
 `pddVlrTotal` decimal(10,0) DEFAULT NULL,
 `pddForn` int DEFAULT NULL,
 PRIMARY KEY (`pddCod`),
 KEY `fk_pedidos_clientes` (`pddCli`),
 KEY `fk_pedidos_fornec` (`pddForn`),
 KEY `fk_pedidos_tipoMov` (`pddTipo`),
 CONSTRAINT `fk_pedidos_clientes` FOREIGN KEY (`pddCli`) REFERENCES `CLIENTES` (`CLICODIGO`),
 CONSTRAINT `fk_pedidos_fornec` FOREIGN KEY (`pddForn`) REFERENCES `FORNECEDORES` (`FRNCODIGO`),
 CONSTRAINT `fk_pedidos_tipoMov` FOREIGN KEY (`pddTipo`) REFERENCES `TIPO_MOVIMENTO` (`tpmCodigo`)
);